export const {
    PORT = 3000,
    SALT_ROUNDS = 10,
    SECRET_JWT_KEY = 'ASLKDMASNJILDNAJSKA$ALMÑSND,%ASDLÑMASD$_ASKLNKLASFKNJKCKOLCKCJKZSOJKCJKLMSACJIO',
    REFRESH_JWT_KEY = 'ASDJKASBNDAq@AASDMKODC2133V/%&yYASD.,FCLMZ'
} = process.env